# Generated by Django 4.1 on 2022-11-05 07:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_VHT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VHTIDN', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('First_Name', models.CharField(max_length=50)),
                ('Middle_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('DOB', models.DateField(max_length=50)),
                ('Phone_Number', models.CharField(max_length=15)),
                ('Email_Address', models.CharField(max_length=50)),
                ('Nationality', models.CharField(max_length=50)),
                ('Region', models.CharField(choices=[('Central ', 'Central '), ('Northern', 'Northern'), ('West Nile', 'West Nile'), ('Western', 'Western'), ('Eastern', 'Eastern')], default='Central', max_length=50)),
                ('District', models.CharField(max_length=50)),
                ('Constitutuency', models.CharField(max_length=100)),
                ('SubCounty', models.CharField(max_length=50)),
                ('Parish_or_Ward', models.CharField(max_length=50)),
                ('Village_or_Zone', models.CharField(max_length=50)),
                ('Occupation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Report_Death',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_IDNO', models.CharField(max_length=20)),
                ('First_Name', models.CharField(max_length=50)),
                ('Middle_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Date_of_Death', models.DateField()),
                ('District', models.CharField(max_length=50)),
                ('Constitutuency', models.CharField(max_length=100)),
                ('SubCounty', models.CharField(max_length=50)),
                ('Parish_or_Ward', models.CharField(max_length=50)),
                ('Village_or_Zone', models.CharField(max_length=50)),
                ('Region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='population.register_vht')),
            ],
        ),
        migrations.CreateModel(
            name='Register_People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UPIDN', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('First_Name', models.CharField(max_length=50)),
                ('Middle_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('DOB', models.DateField()),
                ('Marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], default='Single', max_length=20)),
                ('Disability', models.CharField(choices=[('None', 'None'), ('Deaf', 'Deaf'), ('Cripple', 'Cripple')], default='None', max_length=20)),
                ('Nationality', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=50)),
                ('Constitutuency', models.CharField(max_length=100)),
                ('SubCounty', models.CharField(max_length=50)),
                ('Parish_or_Ward', models.CharField(max_length=50)),
                ('Village_or_Zone', models.CharField(max_length=50)),
                ('Occupation', models.CharField(max_length=50)),
                ('Region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='population.register_vht')),
            ],
        ),
        migrations.CreateModel(
            name='Register_Birth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Birth_Certificate_Number', models.CharField(max_length=40)),
                ('First_Name', models.CharField(max_length=50)),
                ('Middle_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('DOB', models.DateField()),
                ('Place_of_Birth', models.CharField(max_length=50)),
                ('Nationality', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=50)),
                ('Constitutuency', models.CharField(max_length=100)),
                ('SubCounty', models.CharField(max_length=50)),
                ('Parish_or_Ward', models.CharField(max_length=50)),
                ('Village_or_Zone', models.CharField(max_length=50)),
                ('Region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='population.register_vht')),
            ],
        ),
    ]
