# Generated by Django 4.1 on 2022-11-10 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('population', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_death',
            name='Gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='population.register_people'),
        ),
    ]
