# Generated by Django 4.1 on 2022-11-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('population', '0005_alter_register_vht_vhtidn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_people',
            name='UPIDN',
            field=models.CharField(max_length=50),
        ),
    ]
