# Generated by Django 4.1 on 2022-11-13 12:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('population', '0006_alter_register_people_upidn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_birth',
            name='Birth_Certificate_Number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
